### ISSUE TITLE
How did you group your navbar by category under documentation?

### ISSUE THREAD

**Issue by williamrussellajb** [owen2345/camaleon-cms#256]
How did you group your navbar by category under documentation?

http://camaleon.tuzitio.com/documentation/category/

I'm trying to do something like this, but having a hard time grouping everything together. 

What I see is...
the image list:
http://camaleon.tuzitio.com/group/40747-documentation.html

how do you find the category url?

**Comment by owen2345** [comment]
Hi @williamrussellajb 
categories or posts or posttypes or ... yo can do it by:
```
my_cat.the_url # returns the full url for this category
```
return front url for this category
  # args:
  #   locale: language (default current language)
  #   as_path: return the path instead of full url
  #   Also, you can pass extra attributes as params for the url, sample: page.the_url(my_param: 'value', other: "asd")
  #     => http://localhost.com/my-page.html?my_param=value&other=asd
  # Return String URL

**Comment by williamrussellajb** [comment]
I'm currently trying to implement a data-filter. 

I wanted to use "tags" as the id for grouping, or category.

    category = current_site.the_category(@category.the_slug) %>
        <% category.the_posts.decorate.each do |post| %>
        <div class="card"  data-filter=".<%= post.the_tag %>"> 

Im not sure where or how to grab the tags that are on a post.
Thanks!

**Comment by owen2345** [comment]
Tags are relationships like categories:
```
has_many :categories, class_name: "CamaleonCms::Category", through: :term_relationships, :source => :term_taxonomies
  has_many :post_tags, class_name: "CamaleonCms::PostTag", through: :term_relationships, :source => :term_taxonomies
```
Sample:
```
my_post.post_tags ===> return all tags for this post
my_post.categories ==> return all categories for this post
