### ISSUE TITLE
Better to have media in current_site.slug folder

### ISSUE THREAD

**Issue by Uysim** [owen2345/camaleon-cms#272]
I think it would be better if you have option to allow to upload media to current_site.slug/path. I don't want to store my media in current_site.id/path

https://github.com/owen2345/camaleon-cms/blob/master/app/helpers/camaleon_cms/uploader_helper.rb#L74

**Comment by owen2345** [comment]
@Uysim done!
you can add this setting in your system.json to enable the site.slug instead of site.id:
```
"media_slug_folder": true
```
or you can overwrite the method "upload_directory_name" in site model to customize more.
here a sample to customize camaleon class: 
http://camaleon.tuzitio.com/documentation/category/40757-developer-docs/customize-post-type-routes.html

**Comment by Uysim** [comment]
@owen2345  Thank. Please notify me when you deploy this to ruby gem

**Comment by owen2345** [comment]
done!

**Comment by Uysim** [comment]
@owen2345  Thank a lot
