### ISSUE TITLE
MIT License

### ISSUE THREAD

**Issue by herregroen** [owen2345/camaleon-cms#292]
Most Ruby CMS, and gems in general, use the MIT license.

Camaleon CMS is currently using the GNU Affero General Public License.

I would suggest switching to the MIT License. It's used by most dependencies of Camaleon CMS ( rails, cancan, fog etc. ) and would make it much easier for businesses and individuals to start using Camaleon CMS, it's a significantly simpler license.

**Comment by rubyjedi** [comment]
Agreed, switching to the MIT License would open up Camaleon CMS to a wider audience for the above reasons.

**Comment by asn** [comment]
+1 for MIT License

**Comment by carakan** [comment]
+1

**Comment by alexbrinkman** [comment]
+1

**Comment by b264** [comment]
I actually like the idea of using the AGPL to force the product itself to be improved instead of a thousand different forks getting a thousand incompatible improvements that aren't merged back into camaleon (or at least open-sourced)... but I think the point is moot because the AGPL is not backwards-compatible to the MIT so it's too late.  It's copyrighted into the public domain (copyleft) with all rights reserved to the public domain, which includes not using closed-source versions of it.... https://en.wikipedia.org/wiki/License_compatibility#Compatibility_of_FOSS_licenses

**Comment by ChrisFernandez** [comment]
no I will suggest stay with GPL please..

**Comment by owen2345** [comment]
Friends, I changed the license into MIT to have this:
* Commercial Use
* Distribution
* Modification
* Private Use
Regards!
