### ISSUE TITLE
Image custom field

### ISSUE THREAD

**Issue by raulanatol** [owen2345/camaleon-cms#294]
Hi!

Exist any way to include alt, title and caption to image custom fields? 
It's very useful for SEO performance.

Example:
![gallery](https://cloud.githubusercontent.com/assets/2389019/12357636/fb2236f4-bba0-11e5-8c59-7f1afef0ed73.png)

Regards.

**Comment by owen2345** [comment]
Actually, it doesn't. But it would good to add together with this https://github.com/owen2345/camaleon-cms/issues/293

**Comment by mazharoddin** [comment]
Hi @raulanatol  and @owen2345, 
its nice to have caption and title for images, but can you guys please plan to implement updating caption/titles after uploading images instead of while adding it, I feel that way it would be easy for user to upload all images and then edit them to update the title and captions etc if required. 
Please find below screen shot for reference from my old Drupal site( Node gallery module).
<img width="772" alt="screen shot 2016-01-15 at 22 50 30" src="https://cloud.githubusercontent.com/assets/6102465/12359843/7a4b48d8-bbda-11e5-8d46-83eca9907054.png">
.

**Comment by owen2345** [comment]
Hi @raulanatol this functionality was added in the new version 2.2.0 where you can create custom field groups "grouped" (new checkbox in custom field group editor view)

Regards,
