### ISSUE TITLE
File upload size limit

### ISSUE THREAD

**Issue by cmckni3** [owen2345/camaleon-cms#377]
Is there a way to change the maximum file size for uploads?

I see 100 MB is hardcoded. I can't find if there's a way to change it in the UI with the settings hash being passed into the upload_file method.

**Comment by owen2345** [comment]
@cmckni3 
You can customize it by hooks
![screen shot 2016-04-06 at 11 57 23 am](https://cloud.githubusercontent.com/assets/1148415/14323507/d7d1adb8-fbee-11e5-86e9-b579a8c0197c.png)

**Comment by cmckni3** [comment]
I would prefer an easier way to change the default limit

**Comment by cmckni3** [comment]
Maybe a configuration setting?

**Comment by owen2345** [comment]
I will add in settings

**Comment by owen2345** [comment]
@cmckni3: Added, please let me know if it is ok!
![screen shot 2016-04-13 at 4 48 35 pm](https://cloud.githubusercontent.com/assets/1148415/14508880/9a092d90-0197-11e6-8936-217e376faa0a.png)

**Comment by mazharoddin** [comment]
Sorry for jumping into this thread, but I feel it would be good if we create separate tab or section for media, other wise settings section may get clutter very soon, e.g  supporting   different versions of images etc  
Moreover I feel its better to handle  image related settings separately, instead of clubbing into site wide configuration.

**Comment by cmckni3** [comment]
@mazharoddin Agreed. I was thinking more of an env setting for developers/sysadmins to easily change.

**Comment by owen2345** [comment]
what about? a config/camaleon_cms.yml
which can contain those configurations, like:
```
development:
  thumb_size: '100x100'
  max_file_upload: '100' #MB
  ..........
```
Also, move current config/system.json into this yml
What do you think?

**Comment by mazharoddin** [comment]
Hi @cmckni3 & @owen2345, 

Moving these settings to config file will be helpful for developers, but it  doesn't help end user much, since camaleon CMS is targeted for  end user I feel its better we provide option to set these options using UI, but media related config options  should go into separate section (May be in media tab itself ??, this can be helpful if we want to set image settings at sitewide). 

Otherwise "Max file upload size" option can be in File systems settings tab since this setting is for other files along with media, so it makes sense to keep it in File systems settings tab, but thumbnail and other image/media settings should be handled in separate config tab (how about a sub tab named as "general", "image", "video" etc  in "File System config tab" itself). 

But for time being you can plan to  include only "Max file upload size" option along with other existing config options in File system tab. 
Image settings you can plan to add later if there is a plan to gallery module or in media tab or in a sub tab, if image settings are not important for now.

**Comment by owen2345** [comment]
hey @mazharoddin 
You are right!
I added a new tab "Media Settings" for now:
![screen shot 2016-04-27 at 5 14 54 pm](https://cloud.githubusercontent.com/assets/1148415/14868471/af958410-0c9b-11e6-9a23-59472abf6c66.png)

What do you think?

**Comment by cmckni3** [comment]
@mazharoddin True but more than likely something else, e.g. Nginx, will play a role in preventing files higher than a certain size from being uploaded.

**Comment by mazharoddin** [comment]
Thanks @owen2345, you are right cmckni3 ...but  we can try to change the media upload sizes lower than Nginx allowed size, so I guess it should be fine from end user point of view.
