### ISSUE TITLE
How to avoid numeric values in tags

### ISSUE THREAD

**Issue by mazharoddin** [owen2345/camaleon-cms#403]
Hi @owen2345 ,

I observed that tags are getting created as "tag/647-cloud" etc. can you please let me know how we can avoid numeric values in tags.
It would be difficult if we want to migrate data from other CMS to Camaleon due to these numeric values in urls.

**Comment by owen2345** [comment]
Is this the url for tags?

**Comment by mazharoddin** [comment]
@owen2345, yes, URLs are getting created with number values for categories and tags ..it would be great if we can have urls as 'tag/cloud' etc instead of 'tag/647-cloud'.

**Comment by owen2345** [comment]
Hi @mazharoddin it is possible, but there are conflicts, because a posttype have many post tags which permit to enter unique tags per posttype and not per site.
Note: The current idea is to support many groups with their own categories and tags, but this can be customized according to your needs, for example:
If your project only manage one posttype with tags, then you can customize the routes to use this structure "'tag/cloud": 
- Add custom route in your project
```
get 'tag/:slug_tag' => 'frontend#post_tag'
```
- overwrite the method "the_url" for tags to use your custom route
Sample here: http://camaleon.tuzitio.com/documentation/category/40757-developer-docs/customize-post-type-routes.html

Regards,

**Comment by mazharoddin** [comment]
Hi @owen2345, 

Thanks, but I think its good idea to have categories/tags site wide rather posttype wise, as you know all other CMSs and websites use same concept i.e having unique tags/categories site wide, e.g. 'ecommerce' tag/category meaning doesn't change based on posttype right? so it should be better to have categories/tags sitewide.

**Comment by owen2345** [comment]
@mazharoddin that is a good idea, I will work in that idea...!
currently I am creating a video "how to create your theme in 30mins"
Regards,

**Comment by mazharoddin** [comment]
Thanks @owen2345 ...wow great ..video must be useful..thanks

**Comment by mazharoddin** [comment]
Hi @owen2345 , please let me know once this is implemented.

**Comment by mazharoddin** [comment]
Hi @owen2345, 
Pls let me know if this issue is fixed now. Would like to manually migrate my website data to camaleon cms, but because of these numbers in categories, site url paths are getting changed, so it take google to index the pages.
So pls let me know if you fixed this issue so that we have categories without numbers.

**Comment by owen2345** [comment]
Done!
- Added support tag title translatable
- Added simple tag url, sample: http://localhost:3000/tag/mytag.html (this takes the slug and not the title)
Sample use:
```
my_tag.the_basic_url(...)
```

**Comment by mazharoddin** [comment]
Thanks, I will try and let you know.
