### ISSUE TITLE
Feature Request : Crop image

### ISSUE THREAD

**Issue by Uysim** [owen2345/camaleon-cms#439]
I think it would be better to have crop image feature

**Comment by owen2345** [comment]
how should be the process?

**Comment by mazharoddin** [comment]
Hi @owen2345,
I think we can follow same wordpress/drupal approach on cropping image, wordpress shows edit image link if we click on the uploaded image, if we click on that it will show the image in lightbox and provide few options to edit the image, as you might be knowing it allows us to crop and scale the image.
<img width="1182" alt="screen shot 2016-11-05 at 3 57 15 pm" src="https://cloud.githubusercontent.com/assets/6102465/20029404/989af166-a370-11e6-968a-9dc3deebe6b1.png">

I feel cropping/scaling images are required as currently most of the uploaded images are appearing wrongly. 
It would be good if user has option to move the image while cropping/scaling,so that he can select the details which he would like to remove/keep.

<img width="1228" alt="screen shot 2016-11-05 at 3 59 37 pm" src="https://cloud.githubusercontent.com/assets/6102465/20029417/e5114c66-a370-11e6-936b-bdf84773a43c.png">

**Comment by owen2345** [comment]
You are right, I will add for the next version.
Thank you for the idea!

**Comment by mazharoddin** [comment]
Np @owen2345, it would be helpful.
