### ISSUE TITLE
Separate URLs for admin and public site

### ISSUE THREAD

**Issue by p-decoraid** [owen2345/camaleon-cms#507]
Our site is a single page app and as such it has a separate domain name from Camaleon CMS admin. When I am in the admin site, all of the visit links point to the CMS admin domain and are as a result broken. If I change the site to point to the public domain internal Camaleon admin navigation ceases to work.

Desired behavior: ability to specify a URL/domain for the public site separately from URL/domain for the admin area.

**Comment by owen2345** [comment]
Hi @p-decoraid 
it is simple by overwriting this function:
https://github.com/owen2345/camaleon-cms/blob/master/app/helpers/camaleon_cms/site_helper.rb#L3
Regards,

**Comment by p-decoraid** [comment]
We have a single site in camaleon's parlance, which has completely independent urls for the admin area and the public area (think https://admin.foo.com and https://www.foo.com). How is `current_site` relevant here?

**Comment by owen2345** [comment]
It should not be necessary to change the current_site helper because for situations where you have a single site it is returning the first (Only if you have 1 site).
Check my test screenshot where I am accessing to my frontend with http://site1.owen.com:3001 and to my dashboard by http://localhost:3001/admin
