### ISSUE TITLE
Image upload enhancements

### ISSUE THREAD

**Issue by p-decoraid** [owen2345/camaleon-cms#509]
Posting this to get feedback/suggestions etc.

We are looking to improve the process of uploading images for various posts, specifically:
- Have a default s3 prefix per post type, so that each post type has its respective images in its own subfolder
- We use another level of subfolders below post type to group images pertaining to a single post; as such we want the system to remember the last folder the user was in, per post type, so that multiple images can be uploaded to the final subfolder without having to navigate there every image. This cache should expire after some time, I'm thinking 6 hours.

**Comment by mazharoddin** [comment]
yes, this will be helpful.. recently Owen implemented subdomains having specific folders for each site, so this would be nice addition to that.

**Comment by p-decoraid** [comment]
@mazharoddin thanks, can you point me toward that code? I looked through first few pages of commits here and did not see anything appropriate.

**Comment by mazharoddin** [comment]
@p-decoraid , here is the code snippet which @owen2345 modified to add support folder per subdomain.
https://github.com/owen2345/camaleon-cms/blob/master/app/uploaders/camaleon_cms_aws_uploader.rb#L23

**Comment by p-decoraid** [comment]
Thanks @mazharoddin !

**Comment by briank-musichouse** [comment]
I would like this to be an optional feature. The reason is that I have an image compressor hooked up to my S3 bucket that places all optimized images in the same directory. If the function draws files from various subfolders but places them all in one place, then my file management has actually gotten worse.

Another upload feature that would solve this problem would be to add a hook for custom upload processing - image optimization, antivirus, etc. With this in place I could optimize my images before they reach the subfolders, removing the conflict.

**Comment by owen2345** [comment]
@briank-musichouse 
there is a hook for uploader called "before_upload" where you can do it.
Regards,

**Comment by briank-musichouse** [comment]
Sorry, I must have overlooked that. Thanks!
