### ISSUE TITLE
How to migrate website from Drupal to Camaleon_CMS

### ISSUE THREAD

**Issue by mazharoddin** [owen2345/camaleon-cms#536]
Hi @owen2345,

I have couple of websites created using Drupal, I would like to migrate those websites to Camaleon_cms, can you please let me know how i can do it, one website is photo gallery and another one is movies related site, pls let me know how I can migrate it without loosing comments etc.
I would like to migrate below websites.
http://www.mazharuddin.com
http://www.filmydunia.com

**Comment by owen2345** [comment]
Hi @mazharoddin 
To start you need to use the drupal API to read all the information from drupal and maybe you can save in a json format (I am not sure if drupal can export in json/xml format with all data).
After you have the json file, it is easy to import that data in Camaleon CMS because you can add all your custom fields where save the extra data.
Regards,

**Comment by mazharoddin** [comment]
Thanks @owen2345, after we create custom fields we have to import the database? or is there any other way.

**Comment by owen2345** [comment]
you can create the fields in the import process like:
```
pt.add_field({"name"=>"Icon", "slug"=>"service_icon", description: 'Please enter any glyphicon icon'}, {"field_key"=>"text_box", default_value: "glyphicon glyphicon-tint"})
```

**Comment by mazharoddin** [comment]
ok, thanks let me try, Need to check if drupal support json export or not.

**Comment by mazharoddin** [comment]
@owen2345 , I found this ruby file, not sure if its helpful.
https://github.com/contentful/drupal-exporter.rb

**Comment by owen2345** [comment]
great!
