### ISSUE TITLE
How to avoid N+1 queries in CamaleonCms?

### ISSUE THREAD

**Issue by marat-chardymov** [owen2345/camaleon-cms#556]
I'm using bullet to detect N+1 queries. And it complains about custom_fields:
`N+1 Query detected
  CamaleonCms::CustomFieldsRelationship => [:custom_fields]
  Add to your finder: :includes => [:custom_fields]`
Here is my view with query code: 
```ruby
<% @post.get_fields_object.dig(:gallery, :values).each_with_index do |image, index| %>
  <div class="item <%= 'active' if index == 0%>">
    <img src="<%= image %>" />
  </div>
<% end %>
```

**Comment by marat-chardymov** [comment]
Come up with monkey patching, but shouldn't be a better way of doing this?

**Comment by owen2345** [comment]
Solved! please test using github version

**Comment by briank-musichouse** [comment]
I'm getting N+1 query warnings as well, due to a couple of issues.

The first issue is the `draw_menu` method, which in turn calls `cama_draw_menu_items`, which calls `cama_menu_parse_items`. It appears to me that these last two methods may be executing queries within a loop, leading to an N+1 issue.

I also have an issue with a list of links to related posts. When I loop over a group of posts to display a link for each, I get an N+1 warning. I think this is the result of calling `the_url` within the loop, since this method appears to check URL display options on each call. Is there a method for getting a group of post URLs with a single query?

My code:
```
<% posts = current_site.the_posts(@post.post_type.slug).includes(:post_type).latest.limit(7).decorate %>
                <% posts.each do |p| %>
                    <li><a href="<%= p.the_url %>" data-turbolinks="false"><%= p.the_title %></a></li>
                    <% unless p == posts.last %><br><% end %>
```

**Comment by owen2345** [comment]
@briank-musichouse 
1: it is rendering visible menus recursively (depends of qty of menu items), maybe you can cache and use javascript to mark the current menu. (Anyway I will review and improve for the next version)
2: In the first line you can add 
```
mylist.limit(7).eager_load(:my_model).decorate
```
Regards,

**Comment by briank-musichouse** [comment]
Thanks, I'll give it a try.
