### ISSUE TITLE
Using Camaleon alongside existing app

### ISSUE THREAD

**Issue by patricklindsay** [owen2345/camaleon-cms#89]
Is there a way for me to use this gem alongside another app?

I want to be able to use Camaleon as a fully featured blog rather than a CMS.

**Comment by patricklindsay** [comment]
What I mean by this is to be able to harness to the power of the camaleon-cms whilst having control of the routes so that I can add extra content in not controlled through camaleon-cms.

**Comment by owen2345** [comment]
Hello Patrick,
I am not sure if this is what do you want:
Camaleon CMS permit you to integrate your project in the cms like any Ruby on Rails project, i.e. you can create your routes, models, migrations, controllers ..... The advantage is that you can use the helpers and also you can inherit backend and frontend themes by: class CompaniesController < AdminController   or class BussinesController < FrontendController
Please take care to don't overwrite the controllers or models of the cms.
Check screenshots of a real project.
![screen shot 2015-09-22 at 9 03 50 am](https://cloud.githubusercontent.com/assets/1148415/10018903/275524a0-6108-11e5-9ad7-61ee685a0db4.png)
![screen shot 2015-09-22 at 9 03 39 am](https://cloud.githubusercontent.com/assets/1148415/10018904/27591f24-6108-11e5-92c1-8dfc727c9a05.png)
![screen shot 2015-09-22 at 9 03 21 am](https://cloud.githubusercontent.com/assets/1148415/10018905/275aad6c-6108-11e5-8daa-8377d2055527.png)

**Comment by carukc** [comment]
Hello,  Forgive my ignorance... this may be a stupid question but I do not quite understand the answer (I'm fairly new to Ruby).

We have an app that has it's own routes, views, controllers, etc... We need to find a way to integrate a web site so that we can still access a few of our own views, forms, etc (within cameleon) while also providing a more traditional portal for our users.  We also need to manage users in one place so would need to authenticate access via our own user tables.

Our app would handle some routes while Camaleon handles others?

Is this what you mean by "integrate your project in the cms"?

Thanks
Chris

**Comment by owen2345** [comment]
Hi @carukc 
Camaleon CMS can be integrated by two ways:
- As a separated module, like http://mysite.com/myblog/
In this case all routes of camaleon will be whithin http://mysite.com/myblog/
- As as main Module, like http://mysite.com/
In this case all routes will be managed like common site http://mysite.com/

Both permit you to have your custom routes, controllers, locales, ... and also you can overwrite the current camaleon cms routes to show custom contents.
About to manage the same user model you can do it by using the camaleon user model and adding your custom methods/relations, ..., and also you can use the helpers to login/register/logout, ...

Regards,

**Comment by carukc** [comment]
Thank you Owen, That is very helpful.  I'm starting to think that might be best for the user is run 2 URLs... www.domain.com for the portal/CMS all and tools.domain.com for the app.

Since Camaleon will integrate with what we have I guess that means that I use camaleon as the main module on the portal site and then link the app functionality that I want, from our app, into routes.  

That way I get a www landing page for the public with some of our app functionality within this portal and a fully functional app on the tools.domain.com URL.  

Since our app have it's own / the logical problem is how to handle the main route for both and this sidesteps this problem.

Does that make sense or is there a way to do this within one app?

OK... I understand what we need to do re the login.  

Thanks
Chris

**Comment by owen2345** [comment]
Great!
You can overwrite the root_url to use your app / and camaleon root url will be overwritten.
Note: don't forget to share by social networks!

**Comment by carukc** [comment]
Sorry.. I do not quite understand... are you saying that it makes sense to run a parallel app with Camaleon as / with some of our views on routes within that app or that there is a way to have a different / based on URL within one app?

Sorry if this is a dumb question, It seems to make logical sense but I'm new to RoR.

Thanks
Chris

P.S.  We'll definitely spread the word.. Camaleon looks great!

**Comment by owen2345** [comment]
When you install the cms, Camaleon CMS have all required url also home page / 
But you can overwrite this route /  to show your custom / by adding this in your routes.rb
```
root 'my_custom_home#my_custom_function'
```
and when you access by http://mydomain.com/ will be rendered using:
```
my_custom_home#my_custom_function
```

P.S. Sorry for my english!

**Comment by carukc** [comment]
Thanks... It's not so much your English as my rail-speak ;)  I'm just now figuring out how this all works.

**Comment by gentle0219** [comment]
How can I use the camaleon_cms's models on rails console?

**Comment by owen2345** [comment]
like this:
```
Cama::User.first.update(password: 'my_pass', confirm_password: 'my_pass')
```

**Comment by gentle0219** [comment]
Wow Very Thanks :+1:

**Comment by paulitolinhares** [comment]
I have a similar problem to that: I want to create relationships between Camaleon's models and "Non-camaleon" models, for example I want to have related "packages" (`Package.rb`) on my post page, how can I create a `belongs_to` relationship and query it on the camaleon controllers? I'm not sure if I should move this to a different issue or if it's ok to keep it here, either way, let me know what fits best.

Thanks in advance.

**Comment by owen2345** [comment]
@paulitolinhares 
Please check this:
http://camaleon.tuzitio.com/documentation/category/40756-uncategorized/how-to-extend-a-post-model.html

**Comment by paulitolinhares** [comment]
It worked out great, thanks a lot @owen2345!

The only question I have now is how to integrate the post page to show the relationship.

I added the following code to the initializer:
```
Rails.application.config.to_prepare do
  CamaleonCms::Post.class_eval do
    
    has_and_belongs_to_many :locations
  end
end
```
And then created the migration to relate the post and location models. Trying from the console works like a charm, but now I'd like to make for the user to select locations from the database to relate with the post. Can you help with that? I'd figure that it's supposed to work with custom fields but I didn't understand how to do it from the docs.

Thanks a lot in advance.
